### ISSUE TITLE
version 0.15.0 locks up after one flush window

### ISSUE THREAD

**Issue by glennslaven** [atlassian/gostatsd#75]
We're trying gostatsd.  Under load (around 40k incoming metrcs per second) version 0.14.0 recorded it was receiving around 10k metrics per flush window (60s):

```
DEBU[0600] numStats: 10571 packetsReceived: 10537
```

I just tried the new release (0.15) and it locked up after one flush window. That is no more metrics were sent and the app didn't stop when CTRL-C was pressed.  I had to CTRL-Z and `kill` the  pid.

```
./gostatsd_0.15 --flush-interval 60s --verbose --config-path "./config.toml" --metrics-addr "0.0.0.0:8125"                          INFO[0000] Starting server
INFO[0000] No cloud provider specified
INFO[0000] [graphite] address=10.0.0.202:2013 dialTimeout=5s writeTimeout=30s
INFO[0000] Initialised backend "graphite"
DEBU[0060] Sending 2054 metrics to backend graphite
DEBU[0060] Sending 3320 metrics to backend graphite
DEBU[0060] Sending 6079 metrics to backend graphite
DEBU[0060] Sending 1848 metrics to backend graphite
```

config.toml:

```
[graphite]
        address = "10.0.0.202:2013"
        legacy_namespace = false
        global_prefix = "stats"
        prefix_timer = ""
        prefix_counter = ""
```
`10.0.0.202:2013` is carbon relay 

Any idea where I should look to debug this?

We're running on ubuntu 14.04

**Comment by ash2k** [comment]
Try running with `--profile=localhost:6060` and open `http://localhost:6060/debug/pprof/goroutine?debug=2`. There should be the dump of goroutines' stacks.

**Comment by glennslaven** [comment]
Thanks Mikhail,

I've captured 2 sets of stacks:

stack captured immediately after starting, before a flush event: [gostatsd_before.txt](https://github.com/atlassian/gostatsd/files/557286/gostatsd_before.txt)

stack captured after flush event while the process is "stuck": [gostatsd_after.txt](https://github.com/atlassian/gostatsd/files/557287/gostatsd_after.txt)

Only obvious difference is `goroutine 28`.  Before is

```
goroutine 28 [select]:
github.com/atlassian/gostatsd/statsd.(*flusher).Run(0xc4201d81e0, 0xe18580, 0xc420126a00, 0x0, 0x0)
        /gopath/src/github.com/atlassian/gostatsd/statsd/flusher.go:77 +0x1c1
github.com/atlassian/gostatsd/statsd.(*Server).RunWithCustomSocket.func6(0xc4201e3030, 0xe14d00, 0xc4201d81e0, 0xe18580, 0xc420126a00)
        /gopath/src/github.com/atlassian/gostatsd/statsd/statsd.go:263 +0x7d
created by github.com/atlassian/gostatsd/statsd.(*Server).RunWithCustomSocket
        /gopath/src/github.com/atlassian/gostatsd/statsd/statsd.go:266 +0xcd8
```

after is 

```
goroutine 28 [semacquire]:
sync.runtime_Semacquire(0xc42011a1fc)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc42011a1f0)
        /usr/local/go/src/sync/waitgroup.go:131 +0x97
github.com/atlassian/gostatsd/statsd.(*flusher).flushData(0xc4201d81e0, 0xe18580, 0xc420126a00, 0x1)
        /gopath/src/github.com/atlassian/gostatsd/statsd/flusher.go:110 +0x18d
github.com/atlassian/gostatsd/statsd.(*flusher).Run(0xc4201d81e0, 0xe18580, 0xc420126a00, 0x0, 0x0)
        /gopath/src/github.com/atlassian/gostatsd/statsd/flusher.go:81 +0x179
github.com/atlassian/gostatsd/statsd.(*Server).RunWithCustomSocket.func6(0xc4201e3030, 0xe14d00, 0xc4201d81e0, 0xe18580, 0xc420126a00)
        /gopath/src/github.com/atlassian/gostatsd/statsd/statsd.go:263 +0x7d
created by github.com/atlassian/gostatsd/statsd.(*Server).RunWithCustomSocket
        /gopath/src/github.com/atlassian/gostatsd/statsd/statsd.go:266 +0xcd8
```

**Comment by ash2k** [comment]
@glennslaven Sorry for the bug, please give 0.15.1 a try! Thanks for reporting the issue.
